version: '3.8'

services:
  # Service PostgreSQL
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  # Service PHP/Apache pour exécuter l'application Symfony
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - database
    volumes:
      # Monte le dossier du projet (où se trouve le code Symfony) dans /var/www/html
      - .:/var/www/html
    ports:
      - "8000:80"
    environment:
      # Pense à adapter la valeur de DATABASE_URL
      # Nom d'hôte : "database" (celui du service ci-dessus)
      # user/pass : app / !ChangeMe!
      # db       : app
      DATABASE_URL: "postgresql://app:!ChangeMe!@database:5432/app?serverVersion=16&charset=utf8"
      APP_ENV: dev
    working_dir: /var/www/html

volumes:
  database_data:
